version: '3.7'

services:
  db:
    container_name: "url_shortener_db"
    platform: linux/x86_64
    build:
      context: .
      dockerfile: db.Dockerfile
    # networks:
    #   - default
    restart: always
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3306:3306"
    # setting some env vars to create the DB
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "testdb"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "password"

      
    # we mount a data volume to make sure we don't lose data
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
  api:
    container_name:  "shortener_api"
    # we want to use the image which is build from our Dockerfile
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - "9808:9808"
    # we are depending on the mysql backend
    depends_on:
      - db
    links:
      - db
    # We mount the working dir into the container, handy for development
    # This is what makes the hot reloading work inside of a Docker container
    volumes:
      - .:/app/

networks:
  default:
volumes:
  mysql_data: